from django.urls import path
from Login import views

urlpatterns = [
    path('', views.landing, name="landing"),
    path('auth', views.login, name="login"),
    # path('register/' views)
    path('register/', views.register, name="register"),
    path('auth/', views.login_user, name="login_user"),
    path('index/', views.ClockingView, name="index"),
    path('clock_action/<str:user_id>/', views.clock_action, name="clock_action"),
    path('account', views.account, name="account"),
    path('my_profile/<int:userid>/', views.my_profile, name="my_profile"),
    path('update_profile', views.update_profile, name='update_profile'),
    path('update_info', views.update_info, name='update_info'),
    path('update_emerg', views.update_emerg, name='update_emerg'),
    path('update_family_info', views.update_family_info, name='update_family_info'),
    path('update_education_info', views.update_education_info, name='update_education_info'),
    path('update_experience_info', views.update_experience_info, name='update_experience_info'),
    path('Dashboard/<int:userid>/', views.DashboardApp, name="DashboardApp"),
    path('employees', views.employees, name="employees"),
    path('leave Request/', views.Leave_Request, name="leave_Request"),
    path('resignation', views.resignation, name="resignation"),
    path('termination', views.termination, name="termination"),
    path('employee', views.employee, name="employees.html"),
    path('project_view', views.project_view, name='project_view'),
    path('leaves_view', views.leaves_view, name="leaves_view"),
    path('take_break/<int:dataid>/<int:userid>/', views.take_break, name="take_break"),
    path('end_break/<int:dataid>/<int:userid>/', views.end_break, name="end_break"),
    path('clock_out/<int:dataid>/<int:userid>/', views.clock_out, name="clock_out"),
    path('emp_dash/<int:userid>/', views.emp_dash, name="emp_dash"),
    path('add_project/', views.add_project, name="add_project"),
    path('add_employee', views.Employees, name="add_employee"),
    path('add_leave/<int:userid>/', views.add_leave, name="add_leave"), 
    path('emp_list', views.employees_list, name="emp_list"),
    # path('upload/<int:user_id>/', views.upload_document, name="upload"),
    path('uploads/<int:user_id>/', views.upload_document, name="uploads"),
    path('users/<int:userid>/', views.registered_users, name="users"),
    path('export', views.download_registered_users, name="export"),
    path('create_instance', views.create_employee, name="create_instance"),
    path('verify', views.verify_email, name="verify"),
    path('rest/<str:email>/', views.update_pass, name="rest"),
    # path('get/<int:userid>/', views.unverified, name="get"),
    path('Send/<int:userid>/', views.send, name="Send"),
    path('component/<int:userid>/', views.all_clocked, name="component"),
    path('forgot', views.verify_return, name="forgot"),
    path('download', views.download_clocked_users, name="download"),
]