# Generated by Django 4.2.2 on 2023-11-18 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='clockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('IDNumber', models.CharField(max_length=13)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('geolocation', models.CharField(max_length=255)),
                ('clockin_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('clockout_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('takebreak', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endbreak', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(default='', max_length=80)),
                ('subject', models.CharField(default='', max_length=70)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('compl_date', models.DateField(auto_now_add=True)),
                ('qual_name', models.CharField(default='', max_length=90)),
                ('grade', models.CharField(default='', max_length=78)),
                ('sec_inst', models.CharField(default='', max_length=80)),
                ('sec_subject', models.CharField(default='', max_length=70)),
                ('sec_start_date', models.DateField(auto_now_add=True)),
                ('sec_compl_date', models.DateField(auto_now_add=True)),
                ('sec_qual_name', models.CharField(default='', max_length=90)),
                ('sec_grade', models.CharField(default='', max_length=78)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('token_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('token', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerg_name', models.CharField(default='', max_length=57)),
                ('emerg_rel', models.CharField(default='', max_length=100)),
                ('phone_1', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_2', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('em_name', models.CharField(default='', max_length=57)),
                ('em_rel', models.CharField(default='', max_length=100)),
                ('em_phone_1', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('em_phone_2', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('total_leave_days', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=255)),
                ('project_name', models.CharField(default=None, max_length=255)),
                ('project_role', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=90)),
                ('job_position', models.CharField(default='', max_length=90)),
                ('period_f', models.DateField(auto_now_add=True)),
                ('period_t', models.DateField(auto_now_add=True)),
                ('sec_company_name', models.CharField(default='', max_length=100)),
                ('sec_location', models.CharField(default='', max_length=90)),
                ('sec_job_position', models.CharField(default='', max_length=90)),
                ('sec_period_f', models.DateField(auto_now_add=True)),
                ('sec_period_t', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_member_name', models.CharField(default='', max_length=60)),
                ('fam_rel', models.CharField(default='', max_length=67)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('fam_member_phone', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(default=None, max_length=255)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_leave_days', models.IntegerField(default=15)),
                ('days_left', models.IntegerField(default=15)),
                ('status_choices', models.CharField(default='Pending', max_length=255)),
                ('userid', models.IntegerField()),
                ('description', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Login_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(default='', max_length=15)),
                ('pass_num', models.CharField(default='', max_length=20)),
                ('pass_expdate', models.DateField(auto_now_add=True)),
                ('phone_num', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=95)),
                ('marital_st', models.CharField(max_length=60)),
                ('emp_spouse', models.CharField(max_length=70)),
                ('num_child', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(default=None, max_length=255)),
                ('leader', models.CharField(default=None, max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('github', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='resignation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('noticedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resigndate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='App/static/media')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=250)),
                ('zip_code', models.CharField(default='', max_length=90)),
                ('phone_number', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='', max_length=80)),
                ('report', models.CharField(default='', max_length=95)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(default=None, max_length=13, null=True)),
                ('cell', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=255)),
                ('emp_type', models.CharField(max_length=25)),
                ('postal', models.CharField(max_length=255)),
                ('home_address', models.CharField(default=None, max_length=500, null=True)),
                ('work_address', models.CharField(default=None, max_length=500, null=True)),
                ('postal_address', models.CharField(default=None, max_length=500, null=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('reg_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('terminationtype', models.CharField(max_length=100)),
                ('terminationdate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('noticedate', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('L', 'Leave'), ('R', 'Resignation'), ('T', 'Termination')], max_length=1)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, upload_to='documents/')),
                ('course_name', models.CharField(max_length=255, null=True)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('assign_month', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
